### PR TITLE
adding mip solver

### PR DESCRIPTION
**Pull request by mohamed-helala**

### CODE REVIEW

**Comment by mohamed-helala** [comment]
I added the mip solver.

**Comment by lukpank** [comment]
Thank you for your contribution. I am willing to merge your changes
but I see the following possible improvements which I would like to be
resolved before the merge. Could you improve your pull request by
addressing the following issues (or give me some comments on them):

1. It would be better to not expose C structs in the API as it is
   currently with `Iocp` it would be better to convert it into a Go
   struct containing the C struct (as it is with `glpk.Smcp`):

		type Iocp struct {
			iocp C.glp_iocp
		}

   Instead of exposing function `Init_iocp` (which should be named
   `InitIocp`) I would provide `NewIocp` which returns initialized
   `Iocp`:

		func NewIocp() *Iocp {
			p := new(Iocp)
			C.glp_init_iocp(&p.iocp)
			return p
		}

2. Please run gofmt to fix `MipObjVal() float64{`

3. I would not define

		const (
			ON  = int(C.GLP_ON)
			OFF = int(C.GLP_OFF)
		)

   and instead just use the bool typed parameter with a descriptive
   parameter name in function that use `GLP_ON`/`GLP_OFF` in C, as it is
   done in `Prob.Copy()`.  Affected functions: `Iocp.Presolve`,
   `Iocp.SetPresolve`

4. Method `func (p *Prob) Intopt(param *Iocp)` should return `error`
   using the `OptError` similar to `Prob.Simplex`. As `glp_intopt`
   returns errors from `OptError` (page 72 of glpk doc v4.45).

5. It would be nice if you could add documentation strings to the
   exported functions and types. Currently only `SetColKind` has
   docstring but it taken from `SetColName` so should be replaced.

6. It would be nice if you could provide some toy mip problem and add
   appropriate test to `glpk_test.go`. Such that each function/method
   will be called either in that test or in some other test, for
   example `Iocp.SetPresolve`/`Iocp.Presolve` could be tested
   analogously to `TestSetGetProbName` (or many others). In case of
   `Prob.SetColKind` it will require to add `Prob.ColKind` to test the
   value setting and getting.

Best regards,
Łukasz Pankowski

**Comment by mohamed-helala** [comment]
Sorry for not responding for a while. I was busy doing some work. There is always this debate of creating a wrapper that has the same C interface, or creating one with a different more readable interface. for example, NewIocp in place of glp_init_iocp, bool ON in place of C.GLP_ON and OFF. This for sure adds a go taste for the library but at the same time, an experienced C lang glpk user should take care of the new naming convention. 

As you are the library author and you decided to go with the go taste, I will follow your convention and I will do the necessary modifications.

**Comment by mohamed-helala** [comment]
I solved the issues you raised and added a testing example. Please take a look and merge.

**Pull request merged**
